export enum ErrorCode {
  // Generic
  INTERNAL_SERVER_ERROR = "INTERNAL_SERVER_ERROR",
  VALIDATION_ERROR = "VALIDATION_ERROR",
  BAD_REQUEST = "BAD_REQUEST",
  NOT_FOUND = "NOT_FOUND",
  CONFLICT = "CONFLICT",
  UNAUTHORIZED = "UNAUTHORIZED",
  FORBIDDEN = "FORBIDDEN",

  // Authentication
  INVALID_CREDENTIALS = "INVALID_CREDENTIALS",
  EMAIL_ALREADY_EXISTS = "EMAIL_ALREADY_EXISTS",
  EMAIL_NOT_VERIFIED = "EMAIL_NOT_VERIFIED",
  INVALID_TOKEN = "INVALID_TOKEN",
  TOKEN_EXPIRED = "TOKEN_EXPIRED",
  SESSION_EXPIRED = "SESSION_EXPIRED",
  ACCOUNT_SUSPENDED = "ACCOUNT_SUSPENDED",

  // Database
  DATABASE_ERROR = "DATABASE_ERROR",

  // OAuth
  OAUTH_FAILED = "OAUTH_FAILED",

RATE_LIMITED = "RATE_LIMITED",

SESSION_REVOKED = "SESSION_REVOKED",

SESSION_NOT_FOUND = "SESSION_NOT_FOUND",
USER_NOT_FOUND= "USER_NOT_FOUND",

INVALID_GOOGLE_TOKEN = "INVALID_GOOGLE_TOKEN",

GOOGLE_ACCOUNT_ALREADY_LINKED = "GOOGLE_ACCOUNT_ALREADY_LINKED",

PASSWORD_NOT_SET = "PASSWORD_NOT_SET",
}