export enum ErrorCode {
  // Generic
  INTERNAL_SERVER_ERROR = "INTERNAL_SERVER_ERROR",
  VALIDATION_ERROR = "VALIDATION_ERROR",
  BAD_REQUEST = "BAD_REQUEST",
  NOT_FOUND = "NOT_FOUND",
  CONFLICT = "CONFLICT",
  UNAUTHORIZED = "UNAUTHORIZED",
  FORBIDDEN = "FORBIDDEN",

  // Authentication
  INVALID_CREDENTIALS = "INVALID_CREDENTIALS",
  EMAIL_ALREADY_EXISTS = "EMAIL_ALREADY_EXISTS",
  EMAIL_NOT_VERIFIED = "EMAIL_NOT_VERIFIED",
  INVALID_TOKEN = "INVALID_TOKEN",
  TOKEN_EXPIRED = "TOKEN_EXPIRED",
  SESSION_EXPIRED = "SESSION_EXPIRED",
  ACCOUNT_SUSPENDED = "ACCOUNT_SUSPENDED",

  // Database
  DATABASE_ERROR = "DATABASE_ERROR",

  // OAuth
  OAUTH_FAILED = "OAUTH_FAILED",

RATE_LIMITED = "RATE_LIMITED",

SESSION_REVOKED = "SESSION_REVOKED",

SESSION_NOT_FOUND = "SESSION_NOT_FOUND",
USER_NOT_FOUND= "USER_NOT_FOUND",

INVALID_GOOGLE_TOKEN = "INVALID_GOOGLE_TOKEN",

GOOGLE_ACCOUNT_ALREADY_LINKED = "GOOGLE_ACCOUNT_ALREADY_LINKED",

PASSWORD_NOT_SET = "PASSWORD_NOT_SET",

// User
PROFILE_ALREADY_COMPLETED = "PROFILE_ALREADY_COMPLETED",

PROFILE_NOT_FOUND = "PROFILE_NOT_FOUND",

USERNAME_ALREADY_EXISTS = "USERNAME_ALREADY_EXISTS",

USERNAME_UNAVAILABLE = "USERNAME_UNAVAILABLE",

USERNAME_PROHIBITED = "USERNAME_PROHIBITED",

INVALID_USERNAME = "INVALID_USERNAME",

INVALID_COUNTRY_CODE = "INVALID_COUNTRY_CODE",

INVALID_TIMEZONE = "INVALID_TIMEZONE",

INVALID_FILE_TYPE = "INVALID_FILE_TYPE",

FILE_TOO_LARGE = "FILE_TOO_LARGE",

AVATAR_NOT_FOUND = "AVATAR_NOT_FOUND",

AVATAR_UPLOAD_FAILED = "AVATAR_UPLOAD_FAILED",

INVALID_WORKSPACE_DESCRIPTION = "INVALID_WORKSPACE_DESCRIPTION",

INVALID_WORKSPACE_NAME = "INVALID_WORKSPACE_NAME",

WORKSPACE_NOT_FOUND = "WORKSPACE_NOT_FOUND",

INSUFFICIENT_PERMISSIONS = "INSUFFICIENT_PERMISSIONS",

PERSONAL_WORKSPACE_OPERATION_NOT_ALLOWED = "PERSONAL_WORKSPACE_OPERATION_NOT_ALLOWED",

INVALID_OPERATION = "INVALID_OPERATION",

MEMBER_NOT_FOUND = "MEMBER_NOT_FOUND",

INVITATION_ALREADY_EXISTS = "INVITATION_ALREADY_EXISTS",

MEMBER_ALREADY_EXISTS = "MEMBER_ALREADY_EXISTS",

INVITATION_EXPIRED = "INVITATION_EXPIRED",

INVITATION_NOT_FOUND = "INVITATION_NOT_FOUND",

INVALID_INVITATION = "INVALID_INVITATION",

INVALID_PROJECT_TITLE = "INVALID_PROJECT_TITLE",

INVALID_PROJECT_BUDGET = "INVALID_PROJECT_BUDGET",

INVALID_PROJECT_DESCRIPTION = "INVALID_PROJECT_DESCRIPTION",

INVALID_PROJECT_DURATION = "INVALID_PROJECT_DURATION",

INVALID_PROJECT_DATES = "INVALID_PROJECT_DATES",

PROJECT_NOT_FOUND = "PROJECT_NOT_FOUND",

PROJECT_NOT_EDITABLE = "PROJECT_NOT_EDITABLE",

INVALID_PROJECT_STATUS_TRANSITION = "INVALID_PROJECT_STATUS_TRANSITION",

INVALID_PROJECT_SETUP_STAGE = "INVALID_PROJECT_SETUP_STAGE",

INVALID_AGREEMENT_DURATION = "INVALID_AGREEMENT_DURATION",

INVALID_USER_ID = "INVALID_USER_ID",

INVALID_AGREEMENT_BUDGET = "INVALID_AGREEMENT_BUDGET",

INVALID_AGREEMENT_OUT_OF_SCOPE = "INVALID_AGREEMENT_OUT_OF_SCOPE",

INVALID_AGREEMENT_SCOPE = "INVALID_AGREEMENT_SCOPE",

INVALID_AGREEMENT_DESCRIPTION = "INVALID_AGREEMENT_DESCRIPTION",

INVALID_AGREEMENT_TITLE = "INVALID_AGREEMENT_TITLE",

AGREEMENT_NOT_FOUND = "AGREEMENT_NOT_FOUND",

AGREEMENT_LOCKED = "AGREEMENT_LOCKED",

INVALID_REQUEST = "INVALID_REQUEST",

INVALID_MILESTONE_TITLE = "INVALID_MILESTONE_TITLE",

INVALID_MILESTONE_DESCRIPTION = "INVALID_MILESTONE_DESCRIPTION",

INVALID_MILESTONE_DURATION = "INVALID_MILESTONE_DURATION",

INVALID_PAYMENT_ALLOCATION = "INVALID_PAYMENT_ALLOCATION",

INVALID_REVISION_LIMIT = "INVALID_REVISION_LIMIT",

INVALID_MILESTONE_ORDER = "INVALID_MILESTONE_ORDER",

INVALID_MILESTONE_DEPENDENCY = "INVALID_MILESTONE_DEPENDENCY",

DUPLICATE_MILESTONE_DEPENDENCY = "DUPLICATE_MILESTONE_DEPENDENCY",

MILESTONE_NOT_FOUND = "MILESTONE_NOT_FOUND",

INVALID_EXTENSION_REASON = "INVALID_EXTENSION_REASON",

INVALID_EXTENSION_DAYS = "INVALID_EXTENSION_DAYS",

INVALID_PROJECT_ASSET_NAME = "INVALID_PROJECT_ASSET_NAME",

INVALID_PROJECT_ASSET_DESCRIPTION = "INVALID_PROJECT_ASSET_DESCRIPTION",

INVALID_PROJECT_ASSET_FILES = "INVALID_PROJECT_ASSET_FILES",

INVALID_PROJECT_ASSET_FILE = "INVALID_PROJECT_ASSET_FILE",

INVALID_PROJECT_ASSET_FILE_SIZE = "INVALID_PROJECT_ASSET_FILE_SIZE",

INVALID_PROJECT_ASSET = "INVALID_PROJECT_ASSET",

DUPLICATE_PROJECT_ASSET_FILE = "DUPLICATE_PROJECT_ASSET_FILE",

DUPLICATE_PROJECT_ASSET_PARTICIPANT = "DUPLICATE_PROJECT_ASSET_PARTICIPANT",

PROJECT_ASSET_CREATED = "PROJECT_ASSET_CREATED",

PROJECT_ASSET_UPDATED = "PROJECT_ASSET_UPDATED",

PROJECT_ASSET_DELETED = "PROJECT_ASSET_DELETED",

PROJECT_ASSET_NOT_FOUND = "PROJECT_ASSET_NOT_FOUND",

}